name: Build/release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to release'
        required: true
        default: 'v1.0.0'

jobs:
  release:
    runs-on: windows-latest

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1

      - name: Install Yarn packages
        run: yarn install

      - name: Set Tag Version
        run: |
          version=${{ github.event.inputs.tag_name }}
          if [[ "$version" =~ ^v[0-9]+ ]]; then
            version=${version:1}
          fi
          echo "Updating package.json version to $version"
          npm version --no-git-tag-version $version

      - name: Build Application
        run: yarn build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
