name: Build/release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1

      - name: Install Yarn packages
        run: yarn install

      - name: Build Application
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            yarn build:win
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            yarn build:mac
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            yarn build:linux
          fi

      - name: Get Tag Name
        id: get_tag
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/marknote Setup ${{ env.RELEASE_TAG }}.exe
            dist/marknote-${{ env.RELEASE_TAG }}.dmg
            dist/marknote-${{ env.RELEASE_TAG }}.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
