name: Build/release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1

      - name: Install Yarn packages
        run: yarn install

      - name: Build Applicatiton
        run: yarn build:win

      - name: Get Tag Name
        id: get_tag
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MarkNote-${{ env.RELEASE_TAG }} # タグ名をアーティファクト名に追加
          path: |
            release/*.exe
            release/*.exe.blockmap
            release/*.dmg
            release/*.zip
            release/latest*.yml
