name: Build/release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to release'
        required: true
        default: 'v1.0.0'

jobs:
  release:
    runs-on: windows-latest

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1

      - name: Install Yarn packages
        run: yarn install

      - name: Build Application
        run: yarn build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check if the tag already exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ github.event.inputs.tag_name }}" >/dev/null 2>&1; then
            echo "Tag already exists."
            echo "::set-output name=tag_exists::true"
          else
            echo "Tag does not exist."
            echo "::set-output name=tag_exists::false"
          fi
        shell: bash

      - name: Create a new tag if it does not exist
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
